// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (name, starts_at, ends_at)
VALUES ($1, $2, $3)
RETURNING id, name, starts_at, ends_at, created_at, updated_at
`

type CreateEventParams struct {
	Name     string             `json:"name"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.Name, arg.StartsAt, arg.EndsAt)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSeat = `-- name: CreateSeat :one
INSERT INTO seats (event_id, section, row_name, seat_number)
VALUES ($1, $2, $3, $4)
RETURNING id, event_id, section, row_name, seat_number, created_at, updated_at
`

type CreateSeatParams struct {
	EventID    pgtype.UUID `json:"event_id"`
	Section    string      `json:"section"`
	RowName    string      `json:"row_name"`
	SeatNumber string      `json:"seat_number"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, createSeat,
		arg.EventID,
		arg.Section,
		arg.RowName,
		arg.SeatNumber,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Section,
		&i.RowName,
		&i.SeatNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketType = `-- name: CreateTicketType :one
INSERT INTO ticket_types (event_id, name, total_quantity)
VALUES ($1, $2, $3)
RETURNING id, event_id, name, total_quantity, sold_quantity, reserved_quantity, created_at, updated_at
`

type CreateTicketTypeParams struct {
	EventID       pgtype.UUID `json:"event_id"`
	Name          string      `json:"name"`
	TotalQuantity int32       `json:"total_quantity"`
}

func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, createTicketType, arg.EventID, arg.Name, arg.TotalQuantity)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.TotalQuantity,
		&i.SoldQuantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, name, starts_at, ends_at, created_at, updated_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSeatInventoryByEvent = `-- name: ListSeatInventoryByEvent :many
SELECT
    s.id,
    s.event_id,
    s.section,
    s.row_name,
    s.seat_number,
    CASE
        WHEN rs.status = 'confirmed' THEN 'confirmed'
        WHEN rs.status = 'reserved' THEN 'reserved'
        ELSE 'available'
    END AS status
FROM seats AS s
LEFT JOIN reservation_seats AS rs
    ON rs.seat_id = s.id
    AND rs.status IN ('reserved', 'confirmed')
WHERE s.event_id = $1
ORDER BY s.section, s.row_name, s.seat_number, s.id
`

type ListSeatInventoryByEventRow struct {
	ID         pgtype.UUID `json:"id"`
	EventID    pgtype.UUID `json:"event_id"`
	Section    string      `json:"section"`
	RowName    string      `json:"row_name"`
	SeatNumber string      `json:"seat_number"`
	Status     string      `json:"status"`
}

func (q *Queries) ListSeatInventoryByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListSeatInventoryByEventRow, error) {
	rows, err := q.db.Query(ctx, listSeatInventoryByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeatInventoryByEventRow{}
	for rows.Next() {
		var i ListSeatInventoryByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.RowName,
			&i.SeatNumber,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatsByEvent = `-- name: ListSeatsByEvent :many
SELECT id, event_id, section, row_name, seat_number, created_at, updated_at
FROM seats
WHERE event_id = $1
ORDER BY section, row_name, seat_number, id
`

func (q *Queries) ListSeatsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Seat, error) {
	rows, err := q.db.Query(ctx, listSeatsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.RowName,
			&i.SeatNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypeInventoryByEvent = `-- name: ListTicketTypeInventoryByEvent :many
SELECT
    id,
    event_id,
    name,
    total_quantity,
    sold_quantity,
    reserved_quantity,
    total_quantity - sold_quantity - reserved_quantity AS available_quantity
FROM ticket_types
WHERE event_id = $1
ORDER BY name, id
`

type ListTicketTypeInventoryByEventRow struct {
	ID                pgtype.UUID `json:"id"`
	EventID           pgtype.UUID `json:"event_id"`
	Name              string      `json:"name"`
	TotalQuantity     int32       `json:"total_quantity"`
	SoldQuantity      int32       `json:"sold_quantity"`
	ReservedQuantity  int32       `json:"reserved_quantity"`
	AvailableQuantity int32       `json:"available_quantity"`
}

func (q *Queries) ListTicketTypeInventoryByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListTicketTypeInventoryByEventRow, error) {
	rows, err := q.db.Query(ctx, listTicketTypeInventoryByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketTypeInventoryByEventRow{}
	for rows.Next() {
		var i ListTicketTypeInventoryByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.TotalQuantity,
			&i.SoldQuantity,
			&i.ReservedQuantity,
			&i.AvailableQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypesByEvent = `-- name: ListTicketTypesByEvent :many
SELECT id, event_id, name, total_quantity, sold_quantity, reserved_quantity, created_at, updated_at
FROM ticket_types
WHERE event_id = $1
ORDER BY name, id
`

func (q *Queries) ListTicketTypesByEvent(ctx context.Context, eventID pgtype.UUID) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, listTicketTypesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketType{}
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.TotalQuantity,
			&i.SoldQuantity,
			&i.ReservedQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
