// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Reservation struct {
	ID               pgtype.UUID        `json:"id"`
	EventID          pgtype.UUID        `json:"event_id"`
	VisitorSessionID pgtype.UUID        `json:"visitor_session_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Status           string             `json:"status"`
	ReservationType  string             `json:"reservation_type"`
	IdempotencyKey   string             `json:"idempotency_key"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ReservationItem struct {
	ID            pgtype.UUID        `json:"id"`
	ReservationID pgtype.UUID        `json:"reservation_id"`
	TicketTypeID  pgtype.UUID        `json:"ticket_type_id"`
	Quantity      int32              `json:"quantity"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ReservationSeat struct {
	ID            pgtype.UUID        `json:"id"`
	ReservationID pgtype.UUID        `json:"reservation_id"`
	SeatID        pgtype.UUID        `json:"seat_id"`
	Status        string             `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Seat struct {
	ID         pgtype.UUID        `json:"id"`
	EventID    pgtype.UUID        `json:"event_id"`
	Section    string             `json:"section"`
	RowName    string             `json:"row_name"`
	SeatNumber string             `json:"seat_number"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type TicketType struct {
	ID               pgtype.UUID        `json:"id"`
	EventID          pgtype.UUID        `json:"event_id"`
	Name             string             `json:"name"`
	TotalQuantity    int32              `json:"total_quantity"`
	SoldQuantity     int32              `json:"sold_quantity"`
	ReservedQuantity int32              `json:"reserved_quantity"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type VisitorSession struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	AnonymousTokenHash string             `json:"anonymous_token_hash"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}
