// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AttachUserToVisitorSession(ctx context.Context, arg AttachUserToVisitorSessionParams) (VisitorSession, error)
	ConfirmTicketQuantity(ctx context.Context, arg ConfirmTicketQuantityParams) (ConfirmTicketQuantityRow, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateReservationItem(ctx context.Context, arg CreateReservationItemParams) (ReservationItem, error)
	CreateReservationSeat(ctx context.Context, arg CreateReservationSeatParams) (ReservationSeat, error)
	CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error)
	CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (TicketType, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVisitorSession(ctx context.Context, arg CreateVisitorSessionParams) (VisitorSession, error)
	DeleteStressEvents(ctx context.Context, dollar_1 []pgtype.UUID) (int64, error)
	DeleteStressReservationItems(ctx context.Context, dollar_1 []pgtype.UUID) error
	DeleteStressReservationSeats(ctx context.Context, dollar_1 []pgtype.UUID) error
	DeleteStressReservations(ctx context.Context, dollar_1 []pgtype.UUID) error
	ExpireReservationSeatsByReservationIDs(ctx context.Context, dollar_1 []pgtype.UUID) error
	ExpireReservationsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) error
	GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error)
	GetQuantityReservationByIdempotencyKey(ctx context.Context, arg GetQuantityReservationByIdempotencyKeyParams) (GetQuantityReservationByIdempotencyKeyRow, error)
	GetReservationByID(ctx context.Context, id pgtype.UUID) (Reservation, error)
	GetReservationByIdempotencyKey(ctx context.Context, arg GetReservationByIdempotencyKeyParams) (Reservation, error)
	GetSeatReservationByIdempotencyKey(ctx context.Context, arg GetSeatReservationByIdempotencyKeyParams) ([]GetSeatReservationByIdempotencyKeyRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetVisitorSessionByID(ctx context.Context, id pgtype.UUID) (VisitorSession, error)
	GetVisitorSessionByTokenHash(ctx context.Context, anonymousTokenHash string) (VisitorSession, error)
	ListDuplicateActiveSeatViolations(ctx context.Context) ([]ListDuplicateActiveSeatViolationsRow, error)
	ListExpiredActiveReservationIDsForSeats(ctx context.Context, arg ListExpiredActiveReservationIDsForSeatsParams) ([]pgtype.UUID, error)
	ListExpiredReservationsForUpdate(ctx context.Context, arg ListExpiredReservationsForUpdateParams) ([]Reservation, error)
	ListNegativeTicketQuantityViolations(ctx context.Context) ([]ListNegativeTicketQuantityViolationsRow, error)
	ListOrphanReservationItemViolations(ctx context.Context) ([]ListOrphanReservationItemViolationsRow, error)
	ListOrphanReservationSeatViolations(ctx context.Context) ([]ListOrphanReservationSeatViolationsRow, error)
	ListOversoldTicketQuantityViolations(ctx context.Context) ([]ListOversoldTicketQuantityViolationsRow, error)
	ListReservationItems(ctx context.Context, reservationID pgtype.UUID) ([]ReservationItem, error)
	ListReservationSeats(ctx context.Context, reservationID pgtype.UUID) ([]ReservationSeat, error)
	ListSeatInventoryByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListSeatInventoryByEventRow, error)
	ListSeatsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Seat, error)
	ListStaleExpiredActiveReservationViolations(ctx context.Context, expiresAt pgtype.Timestamptz) ([]ListStaleExpiredActiveReservationViolationsRow, error)
	ListStressEventIDs(ctx context.Context, name string) ([]pgtype.UUID, error)
	ListTicketTypeInventoryByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListTicketTypeInventoryByEventRow, error)
	ListTicketTypesByEvent(ctx context.Context, eventID pgtype.UUID) ([]TicketType, error)
	LockEventSeats(ctx context.Context, arg LockEventSeatsParams) ([]pgtype.UUID, error)
	LockReservationForUpdate(ctx context.Context, id pgtype.UUID) (Reservation, error)
	LockReservationsByID(ctx context.Context, dollar_1 []pgtype.UUID) ([]pgtype.UUID, error)
	ReleaseTicketQuantity(ctx context.Context, arg ReleaseTicketQuantityParams) (ReleaseTicketQuantityRow, error)
	ReserveTicketQuantity(ctx context.Context, arg ReserveTicketQuantityParams) (ReserveTicketQuantityRow, error)
	TouchVisitorSession(ctx context.Context, id pgtype.UUID) (VisitorSession, error)
	UpdateReservationItemsStatus(ctx context.Context, arg UpdateReservationItemsStatusParams) error
	UpdateReservationSeatsStatus(ctx context.Context, arg UpdateReservationSeatsStatusParams) error
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error)
}

var _ Querier = (*Queries)(nil)
