// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmTicketQuantity = `-- name: ConfirmTicketQuantity :one
UPDATE ticket_types
SET reserved_quantity = reserved_quantity - $2,
    sold_quantity = sold_quantity + $2,
    updated_at = now()
WHERE id = $1
  AND reserved_quantity >= $2
RETURNING id, total_quantity, sold_quantity, reserved_quantity
`

type ConfirmTicketQuantityParams struct {
	ID               pgtype.UUID `json:"id"`
	ReservedQuantity int32       `json:"reserved_quantity"`
}

type ConfirmTicketQuantityRow struct {
	ID               pgtype.UUID `json:"id"`
	TotalQuantity    int32       `json:"total_quantity"`
	SoldQuantity     int32       `json:"sold_quantity"`
	ReservedQuantity int32       `json:"reserved_quantity"`
}

func (q *Queries) ConfirmTicketQuantity(ctx context.Context, arg ConfirmTicketQuantityParams) (ConfirmTicketQuantityRow, error) {
	row := q.db.QueryRow(ctx, confirmTicketQuantity, arg.ID, arg.ReservedQuantity)
	var i ConfirmTicketQuantityRow
	err := row.Scan(
		&i.ID,
		&i.TotalQuantity,
		&i.SoldQuantity,
		&i.ReservedQuantity,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
    event_id,
    visitor_session_id,
    user_id,
    status,
    reservation_type,
    idempotency_key,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_id, visitor_session_id, user_id, status, reservation_type, idempotency_key, expires_at, created_at, updated_at
`

type CreateReservationParams struct {
	EventID          pgtype.UUID        `json:"event_id"`
	VisitorSessionID pgtype.UUID        `json:"visitor_session_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Status           string             `json:"status"`
	ReservationType  string             `json:"reservation_type"`
	IdempotencyKey   string             `json:"idempotency_key"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.EventID,
		arg.VisitorSessionID,
		arg.UserID,
		arg.Status,
		arg.ReservationType,
		arg.IdempotencyKey,
		arg.ExpiresAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.VisitorSessionID,
		&i.UserID,
		&i.Status,
		&i.ReservationType,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReservationItem = `-- name: CreateReservationItem :one
INSERT INTO reservation_items (
    reservation_id,
    ticket_type_id,
    quantity,
    status
)
VALUES ($1, $2, $3, $4)
RETURNING id, reservation_id, ticket_type_id, quantity, status, created_at, updated_at
`

type CreateReservationItemParams struct {
	ReservationID pgtype.UUID `json:"reservation_id"`
	TicketTypeID  pgtype.UUID `json:"ticket_type_id"`
	Quantity      int32       `json:"quantity"`
	Status        string      `json:"status"`
}

func (q *Queries) CreateReservationItem(ctx context.Context, arg CreateReservationItemParams) (ReservationItem, error) {
	row := q.db.QueryRow(ctx, createReservationItem,
		arg.ReservationID,
		arg.TicketTypeID,
		arg.Quantity,
		arg.Status,
	)
	var i ReservationItem
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReservationSeat = `-- name: CreateReservationSeat :one
INSERT INTO reservation_seats (
    reservation_id,
    seat_id,
    status,
    expires_at
)
VALUES ($1, $2, $3, $4)
RETURNING id, reservation_id, seat_id, status, expires_at, created_at, updated_at
`

type CreateReservationSeatParams struct {
	ReservationID pgtype.UUID        `json:"reservation_id"`
	SeatID        pgtype.UUID        `json:"seat_id"`
	Status        string             `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateReservationSeat(ctx context.Context, arg CreateReservationSeatParams) (ReservationSeat, error) {
	row := q.db.QueryRow(ctx, createReservationSeat,
		arg.ReservationID,
		arg.SeatID,
		arg.Status,
		arg.ExpiresAt,
	)
	var i ReservationSeat
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.SeatID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireReservationSeatsByReservationIDs = `-- name: ExpireReservationSeatsByReservationIDs :exec
UPDATE reservation_seats
SET status = 'expired',
    updated_at = now()
WHERE reservation_id = ANY($1::uuid[])
  AND status = 'reserved'
`

func (q *Queries) ExpireReservationSeatsByReservationIDs(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expireReservationSeatsByReservationIDs, dollar_1)
	return err
}

const expireReservationsByIDs = `-- name: ExpireReservationsByIDs :exec
UPDATE reservations
SET status = 'expired',
    updated_at = now()
WHERE id = ANY($1::uuid[])
  AND status = 'reserved'
`

func (q *Queries) ExpireReservationsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expireReservationsByIDs, dollar_1)
	return err
}

const getQuantityReservationByIdempotencyKey = `-- name: GetQuantityReservationByIdempotencyKey :one
SELECT
    r.id AS reservation_id,
    r.status,
    r.reservation_type,
    r.expires_at,
    ri.ticket_type_id,
    ri.quantity
FROM reservations AS r
JOIN reservation_items AS ri
    ON ri.reservation_id = r.id
WHERE r.visitor_session_id = $1
  AND r.idempotency_key = $2
  AND r.reservation_type = 'quantity'
ORDER BY ri.id
LIMIT 1
`

type GetQuantityReservationByIdempotencyKeyParams struct {
	VisitorSessionID pgtype.UUID `json:"visitor_session_id"`
	IdempotencyKey   string      `json:"idempotency_key"`
}

type GetQuantityReservationByIdempotencyKeyRow struct {
	ReservationID   pgtype.UUID        `json:"reservation_id"`
	Status          string             `json:"status"`
	ReservationType string             `json:"reservation_type"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	TicketTypeID    pgtype.UUID        `json:"ticket_type_id"`
	Quantity        int32              `json:"quantity"`
}

func (q *Queries) GetQuantityReservationByIdempotencyKey(ctx context.Context, arg GetQuantityReservationByIdempotencyKeyParams) (GetQuantityReservationByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getQuantityReservationByIdempotencyKey, arg.VisitorSessionID, arg.IdempotencyKey)
	var i GetQuantityReservationByIdempotencyKeyRow
	err := row.Scan(
		&i.ReservationID,
		&i.Status,
		&i.ReservationType,
		&i.ExpiresAt,
		&i.TicketTypeID,
		&i.Quantity,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, event_id, visitor_session_id, user_id, status, reservation_type, idempotency_key, expires_at, created_at, updated_at
FROM reservations
WHERE id = $1
`

func (q *Queries) GetReservationByID(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.VisitorSessionID,
		&i.UserID,
		&i.Status,
		&i.ReservationType,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT id, event_id, visitor_session_id, user_id, status, reservation_type, idempotency_key, expires_at, created_at, updated_at
FROM reservations
WHERE visitor_session_id = $1
  AND idempotency_key = $2
`

type GetReservationByIdempotencyKeyParams struct {
	VisitorSessionID pgtype.UUID `json:"visitor_session_id"`
	IdempotencyKey   string      `json:"idempotency_key"`
}

func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, arg GetReservationByIdempotencyKeyParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, arg.VisitorSessionID, arg.IdempotencyKey)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.VisitorSessionID,
		&i.UserID,
		&i.Status,
		&i.ReservationType,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeatReservationByIdempotencyKey = `-- name: GetSeatReservationByIdempotencyKey :many
SELECT
    r.id AS reservation_id,
    r.status,
    r.reservation_type,
    r.expires_at,
    rs.seat_id
FROM reservations AS r
JOIN reservation_seats AS rs
    ON rs.reservation_id = r.id
WHERE r.visitor_session_id = $1
  AND r.idempotency_key = $2
  AND r.reservation_type = 'seats'
ORDER BY rs.seat_id
`

type GetSeatReservationByIdempotencyKeyParams struct {
	VisitorSessionID pgtype.UUID `json:"visitor_session_id"`
	IdempotencyKey   string      `json:"idempotency_key"`
}

type GetSeatReservationByIdempotencyKeyRow struct {
	ReservationID   pgtype.UUID        `json:"reservation_id"`
	Status          string             `json:"status"`
	ReservationType string             `json:"reservation_type"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	SeatID          pgtype.UUID        `json:"seat_id"`
}

func (q *Queries) GetSeatReservationByIdempotencyKey(ctx context.Context, arg GetSeatReservationByIdempotencyKeyParams) ([]GetSeatReservationByIdempotencyKeyRow, error) {
	rows, err := q.db.Query(ctx, getSeatReservationByIdempotencyKey, arg.VisitorSessionID, arg.IdempotencyKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSeatReservationByIdempotencyKeyRow{}
	for rows.Next() {
		var i GetSeatReservationByIdempotencyKeyRow
		if err := rows.Scan(
			&i.ReservationID,
			&i.Status,
			&i.ReservationType,
			&i.ExpiresAt,
			&i.SeatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredActiveReservationIDsForSeats = `-- name: ListExpiredActiveReservationIDsForSeats :many
SELECT DISTINCT reservation_id
FROM reservation_seats
WHERE seat_id = ANY($1::uuid[])
  AND status = 'reserved'
  AND expires_at <= $2
ORDER BY reservation_id
`

type ListExpiredActiveReservationIDsForSeatsParams struct {
	Column1   []pgtype.UUID      `json:"column_1"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListExpiredActiveReservationIDsForSeats(ctx context.Context, arg ListExpiredActiveReservationIDsForSeatsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveReservationIDsForSeats, arg.Column1, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var reservation_id pgtype.UUID
		if err := rows.Scan(&reservation_id); err != nil {
			return nil, err
		}
		items = append(items, reservation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredReservationsForUpdate = `-- name: ListExpiredReservationsForUpdate :many
SELECT id, event_id, visitor_session_id, user_id, status, reservation_type, idempotency_key, expires_at, created_at, updated_at
FROM reservations
WHERE status = 'reserved'
  AND expires_at < $1
ORDER BY expires_at, id
FOR UPDATE SKIP LOCKED
LIMIT $2
`

type ListExpiredReservationsForUpdateParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListExpiredReservationsForUpdate(ctx context.Context, arg ListExpiredReservationsForUpdateParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listExpiredReservationsForUpdate, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.VisitorSessionID,
			&i.UserID,
			&i.Status,
			&i.ReservationType,
			&i.IdempotencyKey,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationItems = `-- name: ListReservationItems :many
SELECT id, reservation_id, ticket_type_id, quantity, status, created_at, updated_at
FROM reservation_items
WHERE reservation_id = $1
ORDER BY ticket_type_id, id
`

func (q *Queries) ListReservationItems(ctx context.Context, reservationID pgtype.UUID) ([]ReservationItem, error) {
	rows, err := q.db.Query(ctx, listReservationItems, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservationItem{}
	for rows.Next() {
		var i ReservationItem
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationSeats = `-- name: ListReservationSeats :many
SELECT id, reservation_id, seat_id, status, expires_at, created_at, updated_at
FROM reservation_seats
WHERE reservation_id = $1
ORDER BY seat_id, id
`

func (q *Queries) ListReservationSeats(ctx context.Context, reservationID pgtype.UUID) ([]ReservationSeat, error) {
	rows, err := q.db.Query(ctx, listReservationSeats, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservationSeat{}
	for rows.Next() {
		var i ReservationSeat
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.SeatID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventSeats = `-- name: LockEventSeats :many
SELECT id
FROM seats
WHERE event_id = $1
  AND id = ANY($2::uuid[])
ORDER BY id
FOR UPDATE
`

type LockEventSeatsParams struct {
	EventID pgtype.UUID   `json:"event_id"`
	Column2 []pgtype.UUID `json:"column_2"`
}

func (q *Queries) LockEventSeats(ctx context.Context, arg LockEventSeatsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockEventSeats, arg.EventID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReservationForUpdate = `-- name: LockReservationForUpdate :one
SELECT id, event_id, visitor_session_id, user_id, status, reservation_type, idempotency_key, expires_at, created_at, updated_at
FROM reservations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockReservationForUpdate(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, lockReservationForUpdate, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.VisitorSessionID,
		&i.UserID,
		&i.Status,
		&i.ReservationType,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockReservationsByID = `-- name: LockReservationsByID :many
SELECT id
FROM reservations
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockReservationsByID(ctx context.Context, dollar_1 []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockReservationsByID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTicketQuantity = `-- name: ReleaseTicketQuantity :one
UPDATE ticket_types
SET reserved_quantity = reserved_quantity - $2,
    updated_at = now()
WHERE id = $1
  AND reserved_quantity >= $2
RETURNING id, total_quantity, sold_quantity, reserved_quantity
`

type ReleaseTicketQuantityParams struct {
	ID               pgtype.UUID `json:"id"`
	ReservedQuantity int32       `json:"reserved_quantity"`
}

type ReleaseTicketQuantityRow struct {
	ID               pgtype.UUID `json:"id"`
	TotalQuantity    int32       `json:"total_quantity"`
	SoldQuantity     int32       `json:"sold_quantity"`
	ReservedQuantity int32       `json:"reserved_quantity"`
}

func (q *Queries) ReleaseTicketQuantity(ctx context.Context, arg ReleaseTicketQuantityParams) (ReleaseTicketQuantityRow, error) {
	row := q.db.QueryRow(ctx, releaseTicketQuantity, arg.ID, arg.ReservedQuantity)
	var i ReleaseTicketQuantityRow
	err := row.Scan(
		&i.ID,
		&i.TotalQuantity,
		&i.SoldQuantity,
		&i.ReservedQuantity,
	)
	return i, err
}

const reserveTicketQuantity = `-- name: ReserveTicketQuantity :one
UPDATE ticket_types
SET reserved_quantity = reserved_quantity + $3
WHERE id = $1
  AND event_id = $2
  AND total_quantity - sold_quantity - reserved_quantity >= $3
RETURNING id, total_quantity, sold_quantity, reserved_quantity
`

type ReserveTicketQuantityParams struct {
	ID               pgtype.UUID `json:"id"`
	EventID          pgtype.UUID `json:"event_id"`
	ReservedQuantity int32       `json:"reserved_quantity"`
}

type ReserveTicketQuantityRow struct {
	ID               pgtype.UUID `json:"id"`
	TotalQuantity    int32       `json:"total_quantity"`
	SoldQuantity     int32       `json:"sold_quantity"`
	ReservedQuantity int32       `json:"reserved_quantity"`
}

func (q *Queries) ReserveTicketQuantity(ctx context.Context, arg ReserveTicketQuantityParams) (ReserveTicketQuantityRow, error) {
	row := q.db.QueryRow(ctx, reserveTicketQuantity, arg.ID, arg.EventID, arg.ReservedQuantity)
	var i ReserveTicketQuantityRow
	err := row.Scan(
		&i.ID,
		&i.TotalQuantity,
		&i.SoldQuantity,
		&i.ReservedQuantity,
	)
	return i, err
}

const updateReservationItemsStatus = `-- name: UpdateReservationItemsStatus :exec
UPDATE reservation_items
SET status = $2,
    updated_at = now()
WHERE reservation_id = $1
  AND status = $3
`

type UpdateReservationItemsStatusParams struct {
	ReservationID pgtype.UUID `json:"reservation_id"`
	Status        string      `json:"status"`
	Status_2      string      `json:"status_2"`
}

func (q *Queries) UpdateReservationItemsStatus(ctx context.Context, arg UpdateReservationItemsStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationItemsStatus, arg.ReservationID, arg.Status, arg.Status_2)
	return err
}

const updateReservationSeatsStatus = `-- name: UpdateReservationSeatsStatus :exec
UPDATE reservation_seats
SET status = $2,
    updated_at = now()
WHERE reservation_id = $1
  AND status = $3
`

type UpdateReservationSeatsStatusParams struct {
	ReservationID pgtype.UUID `json:"reservation_id"`
	Status        string      `json:"status"`
	Status_2      string      `json:"status_2"`
}

func (q *Queries) UpdateReservationSeatsStatus(ctx context.Context, arg UpdateReservationSeatsStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationSeatsStatus, arg.ReservationID, arg.Status, arg.Status_2)
	return err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE reservations
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, event_id, visitor_session_id, user_id, status, reservation_type, idempotency_key, expires_at, created_at, updated_at
`

type UpdateReservationStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservationStatus, arg.ID, arg.Status)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.VisitorSessionID,
		&i.UserID,
		&i.Status,
		&i.ReservationType,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
