// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachUserToVisitorSession = `-- name: AttachUserToVisitorSession :one
UPDATE visitor_sessions
SET
    user_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, anonymous_token_hash, created_at, updated_at, last_seen_at, expires_at
`

type AttachUserToVisitorSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AttachUserToVisitorSession(ctx context.Context, arg AttachUserToVisitorSessionParams) (VisitorSession, error) {
	row := q.db.QueryRow(ctx, attachUserToVisitorSession, arg.ID, arg.UserID)
	var i VisitorSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonymousTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createVisitorSession = `-- name: CreateVisitorSession :one
INSERT INTO visitor_sessions (
    anonymous_token_hash,
    last_seen_at,
    expires_at
)
VALUES ($1, $2, $3)
RETURNING id, user_id, anonymous_token_hash, created_at, updated_at, last_seen_at, expires_at
`

type CreateVisitorSessionParams struct {
	AnonymousTokenHash string             `json:"anonymous_token_hash"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateVisitorSession(ctx context.Context, arg CreateVisitorSessionParams) (VisitorSession, error) {
	row := q.db.QueryRow(ctx, createVisitorSession, arg.AnonymousTokenHash, arg.LastSeenAt, arg.ExpiresAt)
	var i VisitorSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonymousTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getVisitorSessionByID = `-- name: GetVisitorSessionByID :one
SELECT id, user_id, anonymous_token_hash, created_at, updated_at, last_seen_at, expires_at
FROM visitor_sessions
WHERE id = $1
`

func (q *Queries) GetVisitorSessionByID(ctx context.Context, id pgtype.UUID) (VisitorSession, error) {
	row := q.db.QueryRow(ctx, getVisitorSessionByID, id)
	var i VisitorSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonymousTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getVisitorSessionByTokenHash = `-- name: GetVisitorSessionByTokenHash :one
SELECT id, user_id, anonymous_token_hash, created_at, updated_at, last_seen_at, expires_at
FROM visitor_sessions
WHERE anonymous_token_hash = $1
`

func (q *Queries) GetVisitorSessionByTokenHash(ctx context.Context, anonymousTokenHash string) (VisitorSession, error) {
	row := q.db.QueryRow(ctx, getVisitorSessionByTokenHash, anonymousTokenHash)
	var i VisitorSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonymousTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const touchVisitorSession = `-- name: TouchVisitorSession :one
UPDATE visitor_sessions
SET
    last_seen_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, anonymous_token_hash, created_at, updated_at, last_seen_at, expires_at
`

func (q *Queries) TouchVisitorSession(ctx context.Context, id pgtype.UUID) (VisitorSession, error) {
	row := q.db.QueryRow(ctx, touchVisitorSession, id)
	var i VisitorSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonymousTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}
