// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stress_admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStressEvents = `-- name: DeleteStressEvents :execrows
DELETE FROM events
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteStressEvents(ctx context.Context, dollar_1 []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStressEvents, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStressReservationItems = `-- name: DeleteStressReservationItems :exec
DELETE FROM reservation_items
WHERE reservation_id IN (
    SELECT id
    FROM reservations
    WHERE event_id = ANY($1::uuid[])
)
`

func (q *Queries) DeleteStressReservationItems(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStressReservationItems, dollar_1)
	return err
}

const deleteStressReservationSeats = `-- name: DeleteStressReservationSeats :exec
DELETE FROM reservation_seats
WHERE reservation_id IN (
    SELECT id
    FROM reservations
    WHERE event_id = ANY($1::uuid[])
)
`

func (q *Queries) DeleteStressReservationSeats(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStressReservationSeats, dollar_1)
	return err
}

const deleteStressReservations = `-- name: DeleteStressReservations :exec
DELETE FROM reservations
WHERE event_id = ANY($1::uuid[])
`

func (q *Queries) DeleteStressReservations(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStressReservations, dollar_1)
	return err
}

const listDuplicateActiveSeatViolations = `-- name: ListDuplicateActiveSeatViolations :many
SELECT
    seat_id,
    COUNT(*)::bigint AS active_count
FROM reservation_seats
WHERE status IN ('reserved', 'confirmed')
GROUP BY seat_id
HAVING COUNT(*) > 1
ORDER BY seat_id
`

type ListDuplicateActiveSeatViolationsRow struct {
	SeatID      pgtype.UUID `json:"seat_id"`
	ActiveCount int64       `json:"active_count"`
}

func (q *Queries) ListDuplicateActiveSeatViolations(ctx context.Context) ([]ListDuplicateActiveSeatViolationsRow, error) {
	rows, err := q.db.Query(ctx, listDuplicateActiveSeatViolations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateActiveSeatViolationsRow{}
	for rows.Next() {
		var i ListDuplicateActiveSeatViolationsRow
		if err := rows.Scan(&i.SeatID, &i.ActiveCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNegativeTicketQuantityViolations = `-- name: ListNegativeTicketQuantityViolations :many
SELECT
    id,
    total_quantity,
    sold_quantity,
    reserved_quantity
FROM ticket_types
WHERE total_quantity < 0
   OR sold_quantity < 0
   OR reserved_quantity < 0
ORDER BY id
`

type ListNegativeTicketQuantityViolationsRow struct {
	ID               pgtype.UUID `json:"id"`
	TotalQuantity    int32       `json:"total_quantity"`
	SoldQuantity     int32       `json:"sold_quantity"`
	ReservedQuantity int32       `json:"reserved_quantity"`
}

func (q *Queries) ListNegativeTicketQuantityViolations(ctx context.Context) ([]ListNegativeTicketQuantityViolationsRow, error) {
	rows, err := q.db.Query(ctx, listNegativeTicketQuantityViolations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNegativeTicketQuantityViolationsRow{}
	for rows.Next() {
		var i ListNegativeTicketQuantityViolationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TotalQuantity,
			&i.SoldQuantity,
			&i.ReservedQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanReservationItemViolations = `-- name: ListOrphanReservationItemViolations :many
SELECT
    ri.id AS reservation_item_id,
    ri.reservation_id
FROM reservation_items AS ri
LEFT JOIN reservations AS r
    ON r.id = ri.reservation_id
WHERE r.id IS NULL
ORDER BY ri.id
`

type ListOrphanReservationItemViolationsRow struct {
	ReservationItemID pgtype.UUID `json:"reservation_item_id"`
	ReservationID     pgtype.UUID `json:"reservation_id"`
}

func (q *Queries) ListOrphanReservationItemViolations(ctx context.Context) ([]ListOrphanReservationItemViolationsRow, error) {
	rows, err := q.db.Query(ctx, listOrphanReservationItemViolations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrphanReservationItemViolationsRow{}
	for rows.Next() {
		var i ListOrphanReservationItemViolationsRow
		if err := rows.Scan(&i.ReservationItemID, &i.ReservationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanReservationSeatViolations = `-- name: ListOrphanReservationSeatViolations :many
SELECT
    rs.id AS reservation_seat_id,
    rs.reservation_id
FROM reservation_seats AS rs
LEFT JOIN reservations AS r
    ON r.id = rs.reservation_id
WHERE r.id IS NULL
ORDER BY rs.id
`

type ListOrphanReservationSeatViolationsRow struct {
	ReservationSeatID pgtype.UUID `json:"reservation_seat_id"`
	ReservationID     pgtype.UUID `json:"reservation_id"`
}

func (q *Queries) ListOrphanReservationSeatViolations(ctx context.Context) ([]ListOrphanReservationSeatViolationsRow, error) {
	rows, err := q.db.Query(ctx, listOrphanReservationSeatViolations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrphanReservationSeatViolationsRow{}
	for rows.Next() {
		var i ListOrphanReservationSeatViolationsRow
		if err := rows.Scan(&i.ReservationSeatID, &i.ReservationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOversoldTicketQuantityViolations = `-- name: ListOversoldTicketQuantityViolations :many
SELECT
    id,
    total_quantity,
    sold_quantity,
    reserved_quantity
FROM ticket_types
WHERE sold_quantity + reserved_quantity > total_quantity
ORDER BY id
`

type ListOversoldTicketQuantityViolationsRow struct {
	ID               pgtype.UUID `json:"id"`
	TotalQuantity    int32       `json:"total_quantity"`
	SoldQuantity     int32       `json:"sold_quantity"`
	ReservedQuantity int32       `json:"reserved_quantity"`
}

func (q *Queries) ListOversoldTicketQuantityViolations(ctx context.Context) ([]ListOversoldTicketQuantityViolationsRow, error) {
	rows, err := q.db.Query(ctx, listOversoldTicketQuantityViolations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOversoldTicketQuantityViolationsRow{}
	for rows.Next() {
		var i ListOversoldTicketQuantityViolationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TotalQuantity,
			&i.SoldQuantity,
			&i.ReservedQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleExpiredActiveReservationViolations = `-- name: ListStaleExpiredActiveReservationViolations :many
SELECT
    id,
    status,
    expires_at
FROM reservations
WHERE status = 'reserved'
  AND expires_at < $1
ORDER BY expires_at, id
`

type ListStaleExpiredActiveReservationViolationsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListStaleExpiredActiveReservationViolations(ctx context.Context, expiresAt pgtype.Timestamptz) ([]ListStaleExpiredActiveReservationViolationsRow, error) {
	rows, err := q.db.Query(ctx, listStaleExpiredActiveReservationViolations, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleExpiredActiveReservationViolationsRow{}
	for rows.Next() {
		var i ListStaleExpiredActiveReservationViolationsRow
		if err := rows.Scan(&i.ID, &i.Status, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStressEventIDs = `-- name: ListStressEventIDs :many
SELECT id
FROM events
WHERE name LIKE $1
ORDER BY id
`

func (q *Queries) ListStressEventIDs(ctx context.Context, name string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listStressEventIDs, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
